spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    username:
    password:
  jmx:
    enabled: false
  liquibase:
    enabled: false


ddl-exporter:
  oracle:
    owner: ${spring.datasource.username}
    dbmsList: oracle
    changePathRelativeToChangeLogPath: true

logging:
  level.com.github.bilak: DEBUG